#!/nfs/slac/g/atlas/u02/cmilke/Anaconda3/bin/python
import sys
sys.path.append('/nfs/slac/g/atlas/u02/cmilke/analysis/util')
from cmilke_analysis_utils import _flavntuple_list_VBFH125_gamgam, _PDG, _Status
import uproot
import pickle

_pt_min = 30 #GeV
_eta_max = 4


D_eta_list = {2:[], 3:[], 4:[]}
branch_list = ['j0pT', 'j0eta', 'j0_isTightPhoton']

for ntuple_file in _flavntuple_list_VBFH125_gamgam:
    tree = uproot.rootio.open(ntuple_file)['Nominal']
    for basket_number, basket in enumerate( tree.iterate(branches=branch_list, entrysteps=10000) ):
        print('Basket: ' + str(basket_number) )
        for event in zip(*basket.values()):
            pt_eta_list = []
            for j0pT, j0eta, j0_isTightPhoton in zip(*event):
                if not j0_isTightPhoton and j0pT > _pt_min and abs(j0eta) < _eta_max:
                    pt_eta_list.append( (j0pT, j0eta) )
            if len(pt_eta_list) in D_eta_list:
                pt_eta_list.sort(reverse=True) #get two leading-pT jets
                D_eta = abs( pt_eta_list[0][1] - pt_eta_list[1][1] )
                D_eta_list[len(pt_eta_list)].append(D_eta)
        #if basket_number >= 1: break

pickle.dump( D_eta_list, open('D_eta_list.p', 'wb') )
