#!/nfs/slac/g/atlas/u02/cmilke/Anaconda3/bin/python
import pickle
import numpy
from matplotlib import pyplot as plt
import matplotlib.ticker as ticker

D_eta_list = pickle.load( open('D_eta_list.p', 'rb') )

fig,ax = plt.subplots()
bin_values = numpy.arange(0,8,0.5)
counts, bins, hist = plt.hist(D_eta_list, bins=bin_values)
ax.set_xticks(bins)
plt.xlabel(r'$\Delta \eta$')
plt.title(r'$\Delta \eta$ of Two Leading-$p_t$ Jets')
plt.grid(True)
plt.show()
fig.savefig('fig_Deta.pdf')
